const employeeLifecycleFlow = {
  nodes: [
    { id: 'start', type: 'input', position: { x: 50, y: 50 }, data: { label: '📞 Persona Contacta\nOrange Staffing' }, className: 'node-info' },
    { id: 'blacklist_check', type: 'default', position: { x: 50, y: 150 }, data: { label: '🔍 Búsqueda\nBlack List' }, className: 'node-warning' },
    { id: 'rejected', type: 'default', position: { x: 250, y: 150 }, data: { label: '❌ RECHAZADO\nNo puede registrarse' }, className: 'node-critical' },
    { id: 'pool_reception', type: 'default', position: { x: 50, y: 250 }, data: { label: '⚪ Pool Recepción\nEsperando asignación' }, className: 'node-info' },
    { id: 'assigned', type: 'default', position: { x: 50, y: 350 }, data: { label: '✅ Asignado a\nRequisición' }, className: 'node-success' },
    { id: 'emp_type_decision', type: 'default', position: { x: 50, y: 450 }, data: { label: '🔀 Tipo de\nEmpleado' }, className: 'node-warning' },
    { id: 'contratista_path', type: 'default', position: { x: 250, y: 400 }, data: { label: '👔 CONTRATISTA' }, className: 'node-success' },
    { id: 'directa_path', type: 'default', position: { x: 250, y: 500 }, data: { label: '👤 PERSONA DIRECTA' }, className: 'node-success' },
    { id: 'both_orange', type: 'default', position: { x: 450, y: 450 }, data: { label: '💰 Ambos empleados\nde Orange Staffing' }, className: 'node-accounting' },
    { id: 'app_0', type: 'default', position: { x: 50, y: 600 }, data: { label: '📱 Aplicación 0%\nInicio proceso' }, className: 'node-info' },
    { id: 'app_30', type: 'default', position: { x: 250, y: 600 }, data: { label: '📋 Aplicación 30%\nInfo Básica' }, className: 'node-warning' },
    { id: 'waiver', type: 'default', position: { x: 450, y: 550 }, data: { label: '📄 Waiver of\nLiability' }, className: 'node-info' },
    { id: 'handbook', type: 'default', position: { x: 450, y: 650 }, data: { label: '📄 Employment\nHandbook' }, className: 'node-info' },
    { id: 'day_1', type: 'default', position: { x: 250, y: 750 }, data: { label: '📅 Día 1 - 8:00 AM\nSe presenta' }, className: 'node-success' },
    { id: 'onboarding', type: 'default', position: { x: 450, y: 750 }, data: { label: '🏆 Inspector\nOnboarding' }, className: 'node-quality' },
    { id: 'working', type: 'default', position: { x: 250, y: 900 }, data: { label: '👔 Empleado Activo\nTrabajando' }, className: 'node-success' },
    { id: 'timeline_72h', type: 'default', position: { x: 500, y: 900 }, data: { label: '⏰ Timeline 72h\nDEADLINE' }, className: 'node-critical' },
    { id: 'r24h', type: 'default', position: { x: 700, y: 800 }, data: { label: '24h: Email +\nNotificación' }, className: 'node-warning' },
    { id: 'r48h', type: 'default', position: { x: 700, y: 880 }, data: { label: '48h: Llamada +\n🟠 NARANJA' }, className: 'node-warning' },
    { id: 'r72h', type: 'default', position: { x: 700, y: 960 }, data: { label: '72h: 🔴 CRÍTICO' }, className: 'node-critical' },
    { id: 'check_60', type: 'default', position: { x: 500, y: 1050 }, data: { label: 'Aplicación\n≥60%?' }, className: 'node-warning' },
    { id: 'strike', type: 'default', position: { x: 700, y: 1050 }, data: { label: '❌ Strike\nInspector' }, className: 'node-critical' },
    { id: 'payment_method', type: 'default', position: { x: 250, y: 1050 }, data: { label: 'Método de\nPago?' }, className: 'node-info' },
    { id: 'validate_bank', type: 'default', position: { x: 100, y: 1150 }, data: { label: '💳 Validar $0.01' }, className: 'node-info' },
    { id: 'check_method', type: 'default', position: { x: 400, y: 1150 }, data: { label: '📄 Cheque' }, className: 'node-info' },
    { id: 'ready_pay', type: 'default', position: { x: 250, y: 1250 }, data: { label: '✅ Validado\npara pago' }, className: 'node-success' },
    { id: 'payroll_note', type: 'default', position: { x: 450, y: 1250 }, data: { label: '💰 Nómina Orange\nDom-Sáb, pago Viernes' }, className: 'node-accounting' },
    { id: 'green_status', type: 'default', position: { x: 250, y: 1350 }, data: { label: '🟢 STATUS VERDE\nListo nómina' }, className: 'node-success' },
    { id: 'uniform_day', type: 'default', position: { x: 50, y: 1450 }, data: { label: '👕 Día 3/5\nUniforme $85' }, className: 'node-quality' },
    { id: 'accounting_notif', type: 'default', position: { x: 250, y: 1450 }, data: { label: '💰 Notificar\nContabilidad' }, className: 'node-accounting' },
    { id: 'collab_pool', type: 'default', position: { x: 450, y: 1450 }, data: { label: '🎯 Pool de\nColaboradores' }, className: 'node-success' },
    { id: 'vacation', type: 'default', position: { x: 650, y: 1450 }, data: { label: '🌴 Vacaciones\n52 semanas' }, className: 'node-info' },
    { id: 'blacklist_final', type: 'default', position: { x: 850, y: 1450 }, data: { label: '🚫 Black List\nPermanente' }, className: 'node-blacklist' },
  ],
  edges: [
    { id: 'e1', source: 'start', target: 'blacklist_check' },
    { id: 'e2', source: 'blacklist_check', target: 'rejected', label: 'Encontrado' },
    { id: 'e3', source: 'blacklist_check', target: 'pool_reception', label: 'No encontrado' },
    { id: 'e4', source: 'pool_reception', target: 'assigned' },
    { id: 'e4b', source: 'assigned', target: 'emp_type_decision' },
    { id: 'e4c', source: 'emp_type_decision', target: 'contratista_path', label: 'Temporal' },
    { id: 'e4d', source: 'emp_type_decision', target: 'directa_path', label: 'Directo' },
    { id: 'e4e', source: 'contratista_path', target: 'both_orange' },
    { id: 'e4f', source: 'directa_path', target: 'both_orange' },
    { id: 'e5', source: 'both_orange', target: 'app_0' },
    { id: 'e6', source: 'app_0', target: 'app_30' },
    { id: 'e7', source: 'app_30', target: 'waiver', style: { strokeDasharray: '5,5' } },
    { id: 'e8', source: 'app_30', target: 'handbook', style: { strokeDasharray: '5,5' } },
    { id: 'e9', source: 'app_30', target: 'day_1' },
    { id: 'e10', source: 'day_1', target: 'onboarding' },
    { id: 'e11', source: 'onboarding', target: 'working' },
    { id: 'e12', source: 'working', target: 'timeline_72h', animated: true },
    { id: 'e13', source: 'timeline_72h', target: 'r24h' },
    { id: 'e14', source: 'r24h', target: 'r48h' },
    { id: 'e15', source: 'r48h', target: 'r72h' },
    { id: 'e16', source: 'r72h', target: 'check_60' },
    { id: 'e17', source: 'check_60', target: 'strike', label: '<60%' },
    { id: 'e18', source: 'check_60', target: 'payment_method', label: '≥60%' },
    { id: 'e19', source: 'payment_method', target: 'validate_bank', label: 'Transfer' },
    { id: 'e20', source: 'payment_method', target: 'check_method', label: 'Check' },
    { id: 'e21', source: 'validate_bank', target: 'ready_pay' },
    { id: 'e22', source: 'check_method', target: 'ready_pay' },
    { id: 'e22b', source: 'ready_pay', target: 'payroll_note' },
    { id: 'e23', source: 'ready_pay', target: 'green_status' },
    { id: 'e24', source: 'green_status', target: 'uniform_day' },
    { id: 'e25', source: 'uniform_day', target: 'accounting_notif', animated: true },
    { id: 'e26', source: 'uniform_day', target: 'collab_pool' },
    { id: 'e27', source: 'collab_pool', target: 'vacation', style: { strokeDasharray: '5,5' } },
    { id: 'e28', source: 'collab_pool', target: 'blacklist_final', style: { strokeDasharray: '5,5' } },
  ]
}

export default employeeLifecycleFlow
