const requisitionsFlow = {
  nodes: [
    { id: 'start', type: 'input', position: { x: 50, y: 50 }, data: { label: '👨‍💼 Manager Hotel\nnecesita personal' }, className: 'node-hotel' },
    { id: 'create', type: 'default', position: { x: 50, y: 150 }, data: { label: '📋 Crear\nRequisición' }, className: 'node-hotel' },
    { id: 'calc_priority', type: 'default', position: { x: 250, y: 150 }, data: { label: 'Calcular\nAnticipación' }, className: 'node-info' },
    { id: 'priority_green', type: 'default', position: { x: 450, y: 50 }, data: { label: '🟢 VERDE\n>120h Normal' }, className: 'node-success' },
    { id: 'priority_yellow', type: 'default', position: { x: 450, y: 150 }, data: { label: '🟡 AMARILLO\n72-120h Media' }, className: 'node-warning' },
    { id: 'priority_red', type: 'default', position: { x: 450, y: 250 }, data: { label: '🔴 ROJO\n<72h Urgente' }, className: 'node-critical' },
    { id: 'gen_req', type: 'default', position: { x: 650, y: 150 }, data: { label: 'Generar Serial\n#' }, className: 'node-info' },
    { id: 'get_contract', type: 'default', position: { x: 850, y: 50 }, data: { label: '📄 Service\nContract' }, className: 'node-accounting' },
    { id: 'get_rates', type: 'default', position: { x: 850, y: 150 }, data: { label: '💰 Bill & Pay\nRate' }, className: 'node-accounting' },
    { id: 'bill_rate', type: 'default', position: { x: 1050, y: 50 }, data: { label: '🏨→Orange\n~$19.58/hr' }, className: 'node-hotel' },
    { id: 'pay_rate', type: 'default', position: { x: 1050, y: 120 }, data: { label: 'Orange→Emp\n~$15/hr' }, className: 'node-success' },
    { id: 'calc_cost', type: 'default', position: { x: 850, y: 250 }, data: { label: '📊 Costos\nProyectados' }, className: 'node-accounting' },
    { id: 'calc_margin', type: 'default', position: { x: 1050, y: 250 }, data: { label: 'Validar\nMargen %' }, className: 'node-accounting' },
    { id: 'margin_ok', type: 'default', position: { x: 1250, y: 150 }, data: { label: '🟢 Margen 30-35%\n($4.58/hr ejemplo)' }, className: 'node-success' },
    { id: 'accounting', type: 'default', position: { x: 1050, y: 350 }, data: { label: '💰 Dashboard\nMónica' }, className: 'node-accounting' },
    { id: 'recruiter', type: 'default', position: { x: 50, y: 400 }, data: { label: '👥 Reclutadora\nCecilia' }, className: 'node-recruitment' },
    { id: 'search', type: 'default', position: { x: 250, y: 400 }, data: { label: '🔍 Búsqueda\nen Pools' }, className: 'node-recruitment' },
    { id: 'filters', type: 'default', position: { x: 450, y: 400 }, data: { label: '⚙️ Filtros\nAutomáticos' }, className: 'node-info' },
    { id: 'distance', type: 'default', position: { x: 650, y: 350 }, data: { label: '📍 Distancia\n≤30 min' }, className: 'node-info' },
    { id: 'availability', type: 'default', position: { x: 650, y: 420 }, data: { label: '📅 Disponibilidad' }, className: 'node-info' },
    { id: 'blacklist', type: 'default', position: { x: 650, y: 490 }, data: { label: '🚫 No Black List' }, className: 'node-warning' },
    { id: 'matches', type: 'default', position: { x: 850, y: 420 }, data: { label: '✅ Matches\nOrdenados' }, className: 'node-success' },
    { id: 'assign', type: 'default', position: { x: 50, y: 600 }, data: { label: '📌 Asignar\nEmpleados' }, className: 'node-recruitment' },
    { id: 'notify_emp', type: 'default', position: { x: 250, y: 600 }, data: { label: '📱 Notificar\nEmpleado' }, className: 'node-info' },
    { id: 'emp_decision', type: 'default', position: { x: 450, y: 600 }, data: { label: 'Empleado\nDecide' }, className: 'node-warning' },
    { id: 'accepts', type: 'default', position: { x: 650, y: 550 }, data: { label: '✅ Acepta' }, className: 'node-success' },
    { id: 'rejects', type: 'default', position: { x: 650, y: 650 }, data: { label: '❌ Rechaza' }, className: 'node-critical' },
    { id: 'complete', type: 'default', position: { x: 850, y: 550 }, data: { label: '📋 Requisición\nCOMPLETADA' }, className: 'node-success' },
    { id: 'tracking', type: 'default', position: { x: 850, y: 650 }, data: { label: '📍 Tracking\nTiempo Real' }, className: 'node-info' },
    { id: 'show', type: 'default', position: { x: 1050, y: 600 }, data: { label: '✅ Presentó\nÉxito' }, className: 'node-success' },
    { id: 'no_show', type: 'default', position: { x: 1050, y: 700 }, data: { label: '❌ NO-SHOW\nPenalización' }, className: 'node-critical' },
  ],
  edges: [
    { id: 'e1', source: 'start', target: 'create' },
    { id: 'e2', source: 'create', target: 'calc_priority' },
    { id: 'e3', source: 'calc_priority', target: 'priority_green', label: '>120h' },
    { id: 'e4', source: 'calc_priority', target: 'priority_yellow', label: '72-120h' },
    { id: 'e5', source: 'calc_priority', target: 'priority_red', label: '<72h' },
    { id: 'e6', source: 'priority_green', target: 'gen_req' },
    { id: 'e7', source: 'priority_yellow', target: 'gen_req' },
    { id: 'e8', source: 'priority_red', target: 'gen_req' },
    { id: 'e9', source: 'gen_req', target: 'get_contract', animated: true, style: { strokeDasharray: '5,5' } },
    { id: 'e10', source: 'get_contract', target: 'get_rates' },
    { id: 'e10b', source: 'get_rates', target: 'bill_rate' },
    { id: 'e10c', source: 'get_rates', target: 'pay_rate' },
    { id: 'e11', source: 'get_rates', target: 'calc_cost' },
    { id: 'e12', source: 'calc_cost', target: 'calc_margin' },
    { id: 'e12b', source: 'bill_rate', target: 'margin_ok', animated: true },
    { id: 'e12c', source: 'pay_rate', target: 'margin_ok', animated: true },
    { id: 'e13', source: 'calc_margin', target: 'margin_ok' },
    { id: 'e14', source: 'calc_margin', target: 'accounting', animated: true },
    { id: 'e15', source: 'gen_req', target: 'recruiter' },
    { id: 'e16', source: 'recruiter', target: 'search' },
    { id: 'e17', source: 'search', target: 'filters' },
    { id: 'e18', source: 'filters', target: 'distance' },
    { id: 'e19', source: 'filters', target: 'availability' },
    { id: 'e20', source: 'filters', target: 'blacklist' },
    { id: 'e21', source: 'distance', target: 'matches' },
    { id: 'e22', source: 'availability', target: 'matches' },
    { id: 'e23', source: 'blacklist', target: 'matches' },
    { id: 'e24', source: 'matches', target: 'assign', style: { strokeDasharray: '5,5' } },
    { id: 'e25', source: 'assign', target: 'notify_emp' },
    { id: 'e26', source: 'notify_emp', target: 'emp_decision' },
    { id: 'e27', source: 'emp_decision', target: 'accepts' },
    { id: 'e28', source: 'emp_decision', target: 'rejects' },
    { id: 'e29', source: 'rejects', target: 'search', style: { stroke: '#c62828' } },
    { id: 'e30', source: 'accepts', target: 'complete' },
    { id: 'e31', source: 'complete', target: 'tracking' },
    { id: 'e32', source: 'tracking', target: 'show' },
    { id: 'e33', source: 'tracking', target: 'no_show' },
  ]
}

export default requisitionsFlow
