const payrollFlow = {
  nodes: [
    // Employee types
    { id: 'emp_types', type: 'default', position: { x: 50, y: 50 }, data: { label: '👥 Empleados Orange\n2 Tipos' }, className: 'node-info' },
    { id: 'contratista', type: 'default', position: { x: 250, y: 20 }, data: { label: '👔 Contratistas' }, className: 'node-success' },
    { id: 'directa', type: 'default', position: { x: 250, y: 80 }, data: { label: '👤 Personas Directas' }, className: 'node-success' },
    { id: 'both_payroll', type: 'default', position: { x: 450, y: 50 }, data: { label: '💰 Ambos en\nNómina Orange' }, className: 'node-accounting' },
    
    // Rates model
    { id: 'rates_model', type: 'default', position: { x: 650, y: 50 }, data: { label: '💵 Modelo de Pago' }, className: 'node-accounting' },
    { id: 'bill_rate', type: 'default', position: { x: 850, y: 20 }, data: { label: '🏨 Hotel → Orange\n$19.58/hr (Bill Rate)' }, className: 'node-hotel' },
    { id: 'pay_rate', type: 'default', position: { x: 850, y: 100 }, data: { label: '💰 Orange → Empleado\n$15/hr (Pay Rate)' }, className: 'node-success' },
    { id: 'margin', type: 'default', position: { x: 1050, y: 60 }, data: { label: '📊 Margen Orange\n30-35% ($4.58/hr)' }, className: 'node-accounting' },
    
    // Weekly cycle
    { id: 'start', type: 'default', position: { x: 50, y: 250 }, data: { label: '📅 Domingo\nInicio Semana' }, className: 'node-info' },
    { id: 'week_note', type: 'default', position: { x: 250, y: 200 }, data: { label: '⚠️ Período típico:\nDom-Sáb\n(3 hoteles diferentes)' }, className: 'node-warning' },
    { id: 'work_week', type: 'default', position: { x: 50, y: 350 }, data: { label: 'Dom-Sáb\nSemana Laboral' }, className: 'node-info' },
    { id: 'punch', type: 'default', position: { x: 250, y: 300 }, data: { label: '⏰ Empleados\nPonchando' }, className: 'node-info' },
    { id: 'hotel_track', type: 'default', position: { x: 250, y: 400 }, data: { label: '🏨 Hotels\nTracking Horas' }, className: 'node-hotel' },
    { id: 'accumulate', type: 'default', position: { x: 450, y: 350 }, data: { label: '📊 Acumulación\nde Horas' }, className: 'node-info' },
    { id: 'deadline', type: 'default', position: { x: 650, y: 350 }, data: { label: '🔴 MIÉRCOLES\n11:59 PM\nDEADLINE' }, className: 'node-critical' },
    { id: 'hotel_report', type: 'default', position: { x: 850, y: 350 }, data: { label: '📊 Hotels reportan\nhoras finales' }, className: 'node-hotel' },
    { id: 'delay_note', type: 'default', position: { x: 1050, y: 350 }, data: { label: '⚠️ DESFASE 1 SEMANA\nPaga semana anterior' }, className: 'node-warning' },
    { id: 'thursday_am', type: 'default', position: { x: 50, y: 550 }, data: { label: '⏰ JUEVES 8 AM\nMónica inicia' }, className: 'node-accounting' },
    { id: 'pre_approval', type: 'default', position: { x: 250, y: 550 }, data: { label: '💰 PRE-APROBACIÓN\nMónica' }, className: 'node-accounting' },
    { id: 'val_1', type: 'default', position: { x: 450, y: 500 }, data: { label: '1️⃣ Horas vs\nReportes' }, className: 'node-info' },
    { id: 'val_2', type: 'default', position: { x: 550, y: 500 }, data: { label: '2️⃣ Info\nPago' }, className: 'node-info' },
    { id: 'val_3', type: 'default', position: { x: 650, y: 500 }, data: { label: '3️⃣ Descuentos' }, className: 'node-info' },
    { id: 'val_4', type: 'default', position: { x: 750, y: 500 }, data: { label: '4️⃣ Vacaciones' }, className: 'node-info' },
    { id: 'val_5', type: 'default', position: { x: 850, y: 500 }, data: { label: '5️⃣ Rates' }, className: 'node-info' },
    { id: 'val_6', type: 'default', position: { x: 450, y: 580 }, data: { label: '6️⃣ Tax ID' }, className: 'node-info' },
    { id: 'val_7', type: 'default', position: { x: 550, y: 580 }, data: { label: '7️⃣ Emp#' }, className: 'node-info' },
    { id: 'val_8', type: 'default', position: { x: 650, y: 580 }, data: { label: '8️⃣ Banking' }, className: 'node-info' },
    { id: 'val_9', type: 'default', position: { x: 750, y: 580 }, data: { label: '9️⃣ Net >$50' }, className: 'node-info' },
    { id: 'val_10', type: 'default', position: { x: 850, y: 580 }, data: { label: '🔟 Gross' }, className: 'node-info' },
    { id: 'val_11', type: 'default', position: { x: 550, y: 660 }, data: { label: '1️⃣1️⃣ Claims' }, className: 'node-info' },
    { id: 'val_12', type: 'default', position: { x: 750, y: 660 }, data: { label: '1️⃣2️⃣ M Lav' }, className: 'node-info' },
    { id: 'discrepancies', type: 'default', position: { x: 250, y: 750 }, data: { label: 'Discrepancias\nencontradas?' }, className: 'node-warning' },
    { id: 'report', type: 'default', position: { x: 450, y: 750 }, data: { label: '📄 Generar\nReporte' }, className: 'node-accounting' },
    { id: 'thursday_pm', type: 'default', position: { x: 650, y: 750 }, data: { label: '⏰ JUEVES 2 PM\nSilvia Revisa' }, className: 'node-critical' },
    { id: 'approve', type: 'default', position: { x: 850, y: 750 }, data: { label: '✅ APROBAR\nNómina Final' }, className: 'node-success' },
    { id: 'thursday_night', type: 'default', position: { x: 50, y: 900 }, data: { label: '⏰ JUEVES 8 PM\nProcesamiento' }, className: 'node-info' },
    { id: 'transfers', type: 'default', position: { x: 250, y: 900 }, data: { label: '💳 Transferencias\nACH 80%+' }, className: 'node-success' },
    { id: 'checks', type: 'default', position: { x: 450, y: 900 }, data: { label: '📄 Cheques\nPaychex <20%' }, className: 'node-info' },
    { id: 'friday', type: 'default', position: { x: 650, y: 900 }, data: { label: '💰 VIERNES 5 AM\nDINERO DISPONIBLE' }, className: 'node-success' },
    { id: 'friday_note', type: 'default', position: { x: 850, y: 900 }, data: { label: '📅 Pago por semana\nDom-Sáb anterior' }, className: 'node-warning' },
    { id: 'claims', type: 'default', position: { x: 50, y: 1050 }, data: { label: '📋 Reclamaciones\n<48h' }, className: 'node-warning' },
    { id: 'end', type: 'output', position: { x: 650, y: 1050 }, data: { label: '✅ NÓMINA\nCOMPLETADA' }, className: 'node-success' },
  ],
  edges: [
    // Employee types
    { id: 'e0a', source: 'emp_types', target: 'contratista' },
    { id: 'e0b', source: 'emp_types', target: 'directa' },
    { id: 'e0c', source: 'contratista', target: 'both_payroll' },
    { id: 'e0d', source: 'directa', target: 'both_payroll' },
    { id: 'e0e', source: 'both_payroll', target: 'rates_model' },
    
    // Rates model
    { id: 'e0f', source: 'rates_model', target: 'bill_rate' },
    { id: 'e0g', source: 'rates_model', target: 'pay_rate' },
    { id: 'e0h', source: 'bill_rate', target: 'margin', animated: true },
    { id: 'e0i', source: 'pay_rate', target: 'margin', animated: true },
    
    // Weekly cycle
    { id: 'e1', source: 'start', target: 'week_note' },
    { id: 'e1b', source: 'start', target: 'work_week' },
    { id: 'e2', source: 'work_week', target: 'punch' },
    { id: 'e3', source: 'work_week', target: 'hotel_track' },
    { id: 'e4', source: 'punch', target: 'accumulate' },
    { id: 'e5', source: 'hotel_track', target: 'accumulate' },
    { id: 'e6', source: 'accumulate', target: 'deadline', animated: true },
    { id: 'e7', source: 'deadline', target: 'hotel_report' },
    { id: 'e7b', source: 'hotel_report', target: 'delay_note' },
    { id: 'e8', source: 'hotel_report', target: 'thursday_am' },
    { id: 'e9', source: 'thursday_am', target: 'pre_approval' },
    { id: 'e10', source: 'pre_approval', target: 'val_1' },
    { id: 'e11', source: 'val_1', target: 'val_2' },
    { id: 'e12', source: 'val_2', target: 'val_3' },
    { id: 'e13', source: 'val_3', target: 'val_4' },
    { id: 'e14', source: 'val_4', target: 'val_5' },
    { id: 'e15', source: 'val_5', target: 'val_6' },
    { id: 'e16', source: 'val_6', target: 'val_7' },
    { id: 'e17', source: 'val_7', target: 'val_8' },
    { id: 'e18', source: 'val_8', target: 'val_9' },
    { id: 'e19', source: 'val_9', target: 'val_10' },
    { id: 'e20', source: 'val_10', target: 'val_11' },
    { id: 'e21', source: 'val_11', target: 'val_12' },
    { id: 'e22', source: 'val_12', target: 'discrepancies' },
    { id: 'e23', source: 'discrepancies', target: 'report', label: 'No' },
    { id: 'e24', source: 'discrepancies', target: 'val_1', label: 'Sí, resolver', style: { stroke: '#c62828' } },
    { id: 'e25', source: 'report', target: 'thursday_pm' },
    { id: 'e26', source: 'thursday_pm', target: 'approve' },
    { id: 'e27', source: 'approve', target: 'thursday_night' },
    { id: 'e28', source: 'thursday_night', target: 'transfers' },
    { id: 'e29', source: 'thursday_night', target: 'checks' },
    { id: 'e30', source: 'transfers', target: 'friday', animated: true },
    { id: 'e31', source: 'checks', target: 'friday' },
    { id: 'e31b', source: 'friday', target: 'friday_note' },
    { id: 'e32', source: 'friday', target: 'claims', style: { strokeDasharray: '5,5' } },
    { id: 'e33', source: 'friday', target: 'end' },
    { id: 'e34', source: 'claims', target: 'end' },
  ]
}

export default payrollFlow
