const qualityFlow = {
  nodes: [
    { id: 'start', type: 'input', position: { x: 50, y: 50 }, data: { label: '🏆 Inspector\nAna García' }, className: 'node-quality' },
    { id: 'dashboard', type: 'default', position: { x: 50, y: 150 }, data: { label: '📊 Dashboard\nInspector' }, className: 'node-quality' },
    { id: 'onboard_assign', type: 'default', position: { x: 250, y: 50 }, data: { label: '🔔 Onboardings\nAsignados' }, className: 'node-warning' },
    { id: 'uniform_deliver', type: 'default', position: { x: 250, y: 150 }, data: { label: '👕 Uniformes\na Entregar' }, className: 'node-quality' },
    { id: 'inspections', type: 'default', position: { x: 250, y: 250 }, data: { label: '🔍 Supervisiones\nProgramadas' }, className: 'node-info' },
    { id: 'incidents', type: 'default', position: { x: 250, y: 350 }, data: { label: '⚠️ Incidentes\nReportados' }, className: 'node-warning' },
    { id: 'new_emp', type: 'default', position: { x: 450, y: 50 }, data: { label: '👤 Empleado Nuevo\nAsignado' }, className: 'node-info' },
    { id: 'day_1', type: 'default', position: { x: 650, y: 50 }, data: { label: '📅 Día 1\n8:00 AM' }, className: 'node-success' },
    { id: 'meet', type: 'default', position: { x: 650, y: 150 }, data: { label: '🤝 Encuentro\nen Propiedad' }, className: 'node-quality' },
    { id: 'help_app', type: 'default', position: { x: 650, y: 250 }, data: { label: '💻 Ayudar\nCompletar App' }, className: 'node-quality' },
    { id: 'target_60', type: 'default', position: { x: 850, y: 150 }, data: { label: '🎯 Meta: 60%\nen 72 horas' }, className: 'node-warning' },
    { id: 'track_72h', type: 'default', position: { x: 850, y: 250 }, data: { label: '⏰ Tracking\n72 Horas' }, className: 'node-critical' },
    { id: 'check_final', type: 'default', position: { x: 1050, y: 200 }, data: { label: 'Aplicación\n≥60%?' }, className: 'node-warning' },
    { id: 'strike', type: 'default', position: { x: 1050, y: 300 }, data: { label: '❌ STRIKE\nal Inspector' }, className: 'node-critical' },
    { id: 'success_onboard', type: 'default', position: { x: 1050, y: 100 }, data: { label: '✅ Onboarding\nExitoso' }, className: 'node-success' },
    { id: 'uniform_ready', type: 'default', position: { x: 450, y: 150 }, data: { label: 'Empleado\nCalifica?' }, className: 'node-warning' },
    { id: 'day_3', type: 'default', position: { x: 450, y: 250 }, data: { label: '📅 Día 3\nFijo' }, className: 'node-quality' },
    { id: 'day_5', type: 'default', position: { x: 450, y: 350 }, data: { label: '📅 Día 5\nTemporal' }, className: 'node-quality' },
    { id: 'prep_uniform', type: 'default', position: { x: 650, y: 300 }, data: { label: '📦 Preparar\nUniforme $85' }, className: 'node-quality' },
    { id: 'deliver', type: 'default', position: { x: 850, y: 350 }, data: { label: '🚗 Ir a\nPropiedad' }, className: 'node-quality' },
    { id: 'sign', type: 'default', position: { x: 850, y: 450 }, data: { label: '✍️ Firma Digital\nen Tablet' }, className: 'node-quality' },
    { id: 'confirm', type: 'default', position: { x: 1050, y: 450 }, data: { label: '✅ Confirmar\nEntrega' }, className: 'node-success' },
    { id: 'notify_accounting', type: 'default', position: { x: 1050, y: 550 }, data: { label: '💰 Notificar\nContabilidad' }, className: 'node-accounting' },
    { id: 'auto_discount', type: 'default', position: { x: 1050, y: 650 }, data: { label: '⚙️ Descuento\nAutomático' }, className: 'node-accounting' },
    { id: 'routes', type: 'default', position: { x: 450, y: 250 }, data: { label: '🗺️ Rutas\nSemanales' }, className: 'node-info' },
    { id: 'visit', type: 'default', position: { x: 450, y: 350 }, data: { label: '🏨 Visitar\nHotel' }, className: 'node-quality' },
    { id: 'check_uniform', type: 'default', position: { x: 450, y: 450 }, data: { label: '✅ Verificar\nUniforme' }, className: 'node-quality' },
    { id: 'check_quality', type: 'default', position: { x: 450, y: 550 }, data: { label: '✅ Verificar\nEstándares' }, className: 'node-quality' },
    { id: 'issues_found', type: 'default', position: { x: 650, y: 500 }, data: { label: 'Problemas\nDetectados?' }, className: 'node-warning' },
    { id: 'inc_minor', type: 'default', position: { x: 450, y: 350 }, data: { label: '📝 Incidente\nMenor' }, className: 'node-warning' },
    { id: 'inc_severe', type: 'default', position: { x: 450, y: 450 }, data: { label: '🔴 Incidente\nGRAVE' }, className: 'node-critical' },
    { id: 'propose_black', type: 'default', position: { x: 650, y: 450 }, data: { label: '🚫 Proponer\nBlack List' }, className: 'node-blacklist' },
    { id: 'direccion', type: 'default', position: { x: 850, y: 450 }, data: { label: '👔 Dirección\nAprueba' }, className: 'node-critical' },
    { id: 'add_blacklist', type: 'output', position: { x: 1050, y: 450 }, data: { label: '🚫 BLACK LIST\nPERMANENTE' }, className: 'node-blacklist' },
  ],
  edges: [
    { id: 'e1', source: 'start', target: 'dashboard' },
    { id: 'e2', source: 'dashboard', target: 'onboard_assign' },
    { id: 'e3', source: 'dashboard', target: 'uniform_deliver' },
    { id: 'e4', source: 'dashboard', target: 'inspections' },
    { id: 'e5', source: 'dashboard', target: 'incidents' },
    { id: 'e6', source: 'onboard_assign', target: 'new_emp' },
    { id: 'e7', source: 'new_emp', target: 'day_1' },
    { id: 'e8', source: 'day_1', target: 'meet' },
    { id: 'e9', source: 'meet', target: 'help_app' },
    { id: 'e10', source: 'help_app', target: 'target_60' },
    { id: 'e11', source: 'target_60', target: 'track_72h', animated: true },
    { id: 'e12', source: 'track_72h', target: 'check_final' },
    { id: 'e13', source: 'check_final', target: 'strike', label: '<60%' },
    { id: 'e14', source: 'check_final', target: 'success_onboard', label: '≥60%' },
    { id: 'e15', source: 'uniform_deliver', target: 'uniform_ready' },
    { id: 'e16', source: 'uniform_ready', target: 'day_3', label: 'Fijo' },
    { id: 'e17', source: 'uniform_ready', target: 'day_5', label: 'Temp' },
    { id: 'e18', source: 'day_3', target: 'prep_uniform' },
    { id: 'e19', source: 'day_5', target: 'prep_uniform' },
    { id: 'e20', source: 'prep_uniform', target: 'deliver' },
    { id: 'e21', source: 'deliver', target: 'sign' },
    { id: 'e22', source: 'sign', target: 'confirm' },
    { id: 'e23', source: 'confirm', target: 'notify_accounting', animated: true },
    { id: 'e24', source: 'notify_accounting', target: 'auto_discount' },
    { id: 'e25', source: 'inspections', target: 'routes' },
    { id: 'e26', source: 'routes', target: 'visit' },
    { id: 'e27', source: 'visit', target: 'check_uniform' },
    { id: 'e28', source: 'check_uniform', target: 'check_quality' },
    { id: 'e29', source: 'check_quality', target: 'issues_found' },
    { id: 'e30', source: 'incidents', target: 'inc_minor' },
    { id: 'e31', source: 'incidents', target: 'inc_severe' },
    { id: 'e32', source: 'inc_severe', target: 'propose_black' },
    { id: 'e33', source: 'propose_black', target: 'direccion' },
    { id: 'e34', source: 'direccion', target: 'add_blacklist', label: 'Aprueba' },
  ]
}

export default qualityFlow
